version: '3.7'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: dev-node
    image: dev-node
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./src:/app/src
    command: yarn start
    environment:
      - MONGO_PATH=mongo:27017/sample
      - WAIT_HOSTS=mongo:27017


  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    container_name: dev-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
      - MONGO_INITDB_DATABASE=sample
    volumes:
      - ../mongo-data/db:/data/db


#  swagger-editor:
#    image: swaggerapi/swagger-editor:latest
#    container_name: "swagger-editor"
#    ports:
#      - "8082:8080"


  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    environment:
      API_URL: /api.yaml
    volumes:
      - ./src/server/api.yml:/usr/share/nginx/html/api.yaml
